### ISSUE TITLE
Blinking horizontal text

### ISSUE THREAD

**Issue by hendras1722** [LoaderB0T/typed.ts#10]
Hello, I have one question. How to show blinking horizontal cursor?

Pls reply because not showing blink cursor

**Comment by LoaderB0T** [comment]
Hi, you'll have to implement the blinking cursor on you own. This library only changes the text itself. The rendering has to be handled by the user
You can find an example here:
https://github.com/LoaderB0T/awdware3/blob/main/web/apps/home/src/app/home/home.component.html#L14

Also check the styles: https://github.com/LoaderB0T/awdware3/blob/main/web/libs/styles/src/lib/_global.scss#L46

I hope this helps you with implementing a blinking cursor on you own.
