### ISSUE TITLE
Issue after build nuxt 3

### ISSUE THREAD

**Issue by hendras1722** [LoaderB0T/typed.ts#32]
<img width="962" alt="image" src="https://github.com/LoaderB0T/typed.ts/assets/57746184/c7972ee2-6d6e-498f-b587-45cda778db3f">

hi can you help me for solve this?

**Comment by LoaderB0T** [comment]
Hi there, I just published a fix with version 3.0.1 that should resolve this issue.

I had broken import/export paths in my code that were missing the file extension.

Please try again with version 3.0.1 and let me know whether that fixed the issue. Thanks & sorry for any inconvenience.
